import Marquee from 'react-fast-marquee';
import { BsEmojiDizzyFill, BsEmojiHeartEyesFill, BsEmojiSmileFill, BsFillEmojiExpressionlessFill, BsFillEmojiGrinFill, BsFillEmojiKissFill, BsFillEmojiWinkFill } from 'react-icons/bs';

function BackGroundEmoji() {
    return (<>
        <Marquee speed={100} className=" absolute z-10 rotate-3">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -rotate-6">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} className=" absolute z-10 rotate-6">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -rotate-3">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} className=" absolute z-10 -rotate-3">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 rotate-6">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} className=" absolute z-10 -rotate-30">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 rotate-30">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
       
      
      
      
     
        <Marquee speed={100} className=" absolute z-10 rotate-2">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -rotate-6">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -translate-y-[400%]  -rotate-6">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -translate-y-[400%]  -rotate-6">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -translate-y-[100%]   -rotate-2">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
        <Marquee speed={100} direction='' className=" absolute z-10 -translate-y-[300%]   rotate-2">
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
            <BsFillEmojiExpressionlessFill />
            <BsEmojiDizzyFill />
            <BsEmojiHeartEyesFill />
            <BsFillEmojiKissFill />
            <BsFillEmojiGrinFill />
            <BsEmojiDizzyFill />
            <BsEmojiSmileFill />
            <BsFillEmojiWinkFill />
        </Marquee>
         
    </>
    )
}

export default BackGroundEmoji
